### ISSUE TITLE
An active user can delete event

### ISSUE THREAD

**Issue by roaldpalaya** [Team-takeTurns/takeTurns#4]

**Comment by liliya0artyuh** [comment]
@ebenezeradejumo, @hlac  
This user story and its relevant tasks will be reassigned to another member if it is not completed by the extended deadline Saturday, Feb 27.

**Comment by liliya0artyuh** [comment]
@ebenezeradejumo, @hlac

Hi Ben,
As per our meeting today the deadline for this task was extended to tomorrow morning.
Please, reply to this comment tomorrow morning before 11am with the status.
Liliya

**Comment by hlac** [comment]
@liliya0artyuh, @ebenezeradejumo 
Thank you, Liliya.  Keep me posted.

**Comment by ebenezeradejumo** [comment]
Completed it, only left with little enhancement. i also created a pull request

**Comment by liliya0artyuh** [comment]
@ebenezeradejumo, @hlac

Thanks, Ebenezer.

**Comment by liliya0artyuh** [comment]
when writing comments please add @ handler + user name in the future. Also if you are closing any tasks use the following in the comment section in the commit statement:
"closes #NumberOfTheTask_1, closes #NumberOfTheTask_2, etc..."
You can get those numbers from the issues list
