### ISSUE TITLE
An active user can edit event

### ISSUE THREAD

**Issue by roaldpalaya** [Team-takeTurns/takeTurns#5]

**Comment by liliya0artyuh** [comment]
@IbrahimNatchee, @hlac  
This user story and its relevant tasks will be reassigned to another member if it is not completed by the extended deadline Saturday, Feb 27.

**Comment by liliya0artyuh** [comment]
@IbrahimNatchee, @hlac, @liliya0artyuh

Hi Abraham,
As per our meeting today you will be teamed up with me to finish this user story. We will meet tomorrow at 11AM to work on this.
The agenda for tomorrow:
1. figure out what has been done already and push that code to GitHub.
2. remaining tasks will be reassigned to me but we will work together on them.

Liliya

**Comment by hlac** [comment]
@liliya0artyuh, @IbrahimNatchee 
Thank you, Liliya.  Keep me posted on your progress with Ibrahim.

**Comment by liliya0artyuh** [comment]
@IbrahimNatchee, @hlac 

I worked with Abraham today and we finished this user story.
