### ISSUE TITLE
An active user can view calendar a month at a time

### ISSUE THREAD

**Issue by roaldpalaya** [Team-takeTurns/takeTurns#6]

**Comment by liliya0artyuh** [comment]
@alexlchen , @hlac  
This user story and its relevant tasks will be reassigned to another member if it is not completed by the extended deadline Saturday, Feb 27.

**Comment by liliya0artyuh** [comment]
@alexlchen, @hlac 
Alex, I got your email with request not to reassign work because you say that you completed it. Please create a pull request to merge the code before our meeting today. In the future, please respond here rather than via email.

**Comment by hlac** [comment]
@alexlchen, @liliya0artyuh 
Alex, I agree with Liliya.

**Comment by liliya0artyuh** [comment]
@alexlchen, @hlac

Hi Alex,
As per our meeting today the deadline for this task was extended to Monday. This extension is conditioned on that you will provide the team to see the functionality that you build in a separate project.
Please, reply to this comment tomorrow morning before 11am with the link to wherever you have the functionality published.
thank you,
Liliya

**Comment by liliya0artyuh** [comment]
@alexlchen, @hlac, @EphermeralCC 

Alex, 
The project you showed me appears to be a copy of this https://github.com/angular-ui/ui-calendar/blob/master/demo/calendarDemo.js
You cannot move it to our project because it is not in angular-fullstack project nor it is customized for our project.
I am sorry but I have to reassign this story because no tasks were completed for it.

Christine, 
do you still have that code for month view. Can you push it to github, please.


Thanks,
Liliya

**Comment by alexlchen** [comment]
I only use its calendar template. I won't copy every thing. I tailor it to fit the take turn project.


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by liliya0artyuh** [comment]
@alexlchen, @hlac, @EphermeralCC

I don't know what to say. 
The project you showed me... as is, it cannot close any tasks. Tailoring will take a while. If 4 weeks was not enough to tailor it then how can it be done in one day?
I saw Christine had some generic month view. I believe we should go with that. We already know that it works in our project and it pulls data from MongoDB. The only parts left is the logic for how to display little details in the view and linking month view to day view. The logic for view needs to be customized to meet customer's requirements. It is a big job actually. If you want to work on this particular user story then you can try working on that perhaps once Christine uploads the UI. So let me know if you want to work on the logic parts. The deadline for logic parts is Friday March 4th at 6PM.

Liliya
