### ISSUE TITLE
Page for Event Viewer does not update automatically

### ISSUE THREAD

**Issue by liliya0artyuh** [Team-takeTurns/takeTurns#80]
View does not update automatically after deleting event. Current workaround is to reload page with <b>window.location.reload(true); </b>.

//code to delete an event
```
            deleteEvent(){
            //change view
                this.showEventDetailView = true;
                this.showEventDetailForm = true;
                console.log("event Id   " +  this.selectedEvent._id);
                console.log("event Id  outside if " + this.calendar._id); 
                this.$http.patch('/api/calendars/' + this.calendar._id +"/DeleteEvent/"+ this.selectedEvent._id).then(response => {
                  this.calendar = response.data;
                window.location.reload(true);
                });
            } 
```

**Comment by liliya0artyuh** [comment]
@Francid 
Hi Francis, Can you confirm if this bug was fixed please?
Liliya

**Comment by Francid** [comment]
Hi Liliya,
The bug is now fixed...
Thank you, Francis Ofougwuka. 
Sent from Yahoo Mail on Android 
 
  On Sun, Apr 3, 2016 at 11:43 AM, liliya0artyuh<notifications@github.com> wrote:   
@Francid 
Hi Francis, Can you confirm if this bug was fixed please?
Liliya
